name: expiali
description: Flutter based decentralized application for dating and networking.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  matrix_api_lite: ^0.2.0
  settings_ui: ^0.6.0
  timeago: ^3.0.2
  enum_to_string: ^2.0.1
  intl: ^0.17.0
  flutter_secure_storage: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito/Nunito-Italic.ttf
          style: italic
        - asset: fonts/Nunito/Nunito-Bold.ttf
          weight: 700